// src/components/auth/RegisterForm.tsx
'use client';

import React, { useState, ChangeEvent, FormEvent } from 'react';
import Link from 'next/link';

interface RegisterFormProps {
    onSubmit: (email: string, password: string) => Promise<void>; // Make onSubmit async
    isLoading: boolean;
}

const RegisterForm: React.FC<RegisterFormProps> = ({ onSubmit, isLoading }) => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [errors, setErrors] = useState({ email: '', password: '', confirmPassword: '' });

    const validateForm = (): boolean => {
        let isValid = true;
        const newErrors = { email: '', password: '', confirmPassword: '' };

        // Email Validation
        if (!email.trim()) {
            newErrors.email = 'Email is required!';
            isValid = false;
        } else if (!/\S+@\S+\.\S+/.test(email)) {
            newErrors.email = 'Invalid email format!';
            isValid = false;
        }

        // Password Validation
        if (!password) {
            newErrors.password = 'Password is required!';
            isValid = false;
        } else if (password.length < 6) {
            newErrors.password = 'Password must be at least 6 characters long!';
            isValid = false;
        }

        // Confirm Password Validation
        if (!confirmPassword) {
            newErrors.confirmPassword = 'Please confirm your password!';
            isValid = false;
        } else if (password !== confirmPassword) {
            newErrors.confirmPassword = 'Passwords do not match!';
            isValid = false;
        }

        setErrors(newErrors);
        return isValid;
    };

    const clearError = (field: keyof typeof errors) => {
        setErrors((prev) => ({ ...prev, [field]: '' }));
    };

    const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!validateForm()) {
            return;
        }
        await onSubmit(email, password); // Call the async onSubmit prop
    };

    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            {/* Email Field */}
            <div>
                <label htmlFor="email" className="form-label">Email</label>
                <input
                    type="email"
                    id="email"
                    value={email}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
                    onFocus={() => clearError('email')}
                    className={`form-control ${errors.email ? 'border-red-500' : 'border-gray-300'}`}
                    aria-describedby="email-error"
                    aria-invalid={!!errors.email}
                    autoComplete="email"
                />
                {errors.email && <p id="email-error" className="mt-1 text-sm text-red-600">{errors.email}</p>}
            </div>

            {/* Password Field */}
            <div>
                <label htmlFor="password" className="form-label">Password</label>
                <input
                    type="password"
                    id="password"
                    value={password}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
                    onFocus={() => clearError('password')}
                    className={`form-control ${errors.password ? 'border-red-500' : 'border-gray-300'}`}
                    aria-describedby="password-error"
                    aria-invalid={!!errors.password}
                    autoComplete="new-password"
                />
                {errors.password && <p id="password-error" className="mt-1 text-sm text-red-600">{errors.password}</p>}
            </div>

            {/* Confirm Password Field */}
            <div>
                <label htmlFor="confirmPassword" className="form-label">Confirm Password</label>
                <input
                    type="password"
                    id="confirmPassword"
                    value={confirmPassword}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setConfirmPassword(e.target.value)}
                    onFocus={() => clearError('confirmPassword')}
                    className={`form-control ${errors.confirmPassword ? 'border-red-500' : 'border-gray-300'}`}
                    aria-describedby="confirmPassword-error"
                    aria-invalid={!!errors.confirmPassword}
                    autoComplete="new-password"
                />
                {errors.confirmPassword && <p id="confirmPassword-error" className="mt-1 text-sm text-red-600">{errors.confirmPassword}</p>}
            </div>

            {/* Submit Button */}
            <button
                type="submit"
                disabled={isLoading}
                className="w-full btn-primary flex justify-center items-center" // Ensure full width and centered content
            >
                {isLoading ? (
                    <>
                        <span className="spinner-border spinner-border-sm mr-2" role="status" aria-hidden="true"></span>
                        Loading...
                    </>
                ) : (
                    'Sign Up'
                )}
            </button>

            {/* Login Link */}
            <div className="text-sm text-center text-gray-600">
                Already have an account?{' '}
                <Link href="/login" className="font-medium text-blue-600 hover:text-blue-700">
                    Sign in
                </Link>
            </div>
        </form>
    );
};

export default RegisterForm;

// src/components/RegisterForm.vue
<template>
  <form class="register-form" @submit.prevent="handleSubmit">
    <div class="form-group">
      <label for="email">Email</label>
      <input
          type="email"
          id="email"
          v-model="registerForm.email"
          :class="{ 'error': errors.email }"
          @focus="clearError('email')"
      />
      <span class="error-message" v-if="errors.email">{{ errors.email }}</span>
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input
          type="password"
          id="password"
          v-model="registerForm.password"
          :class="{ 'error': errors.password }"
          @focus="clearError('password')"
      />
      <span class="error-message" v-if="errors.password">{{ errors.password }}</span>
    </div>

    <div class="form-group">
      <label for="confirmPassword">Confirm Password</label>
      <input
          type="password"
          id="confirmPassword"
          v-model="registerForm.confirmPassword"
          :class="{ 'error': errors.confirmPassword }"
          @focus="clearError('confirmPassword')"
      />
      <span class="error-message" v-if="errors.confirmPassword">{{ errors.confirmPassword }}</span>
    </div>

    <button type="submit" :disabled="isLoading" >
      <span v-if="isLoading" class="spinner-border spinner-border-sm"></span>
      {{ isLoading ? 'Loading...' : 'Sign Up' }}
    </button>

    <div class="login-link">
      Already have an account?
      <router-link to="/login">Sign in</router-link>
    </div>
  </form>
</template>

<script setup>
import { reactive, ref } from 'vue';

const registerForm = reactive({
  email: '',
  password: '',
  confirmPassword: '',
});

const errors = reactive({
  email: '',
  password: '',
  confirmPassword: '',
});

const isLoading = ref(false);

const validateForm = () => {
  let isValid = true;
  errors.email = '';
  errors.password = '';
  errors.confirmPassword = '';

  if (!registerForm.email.trim()) {
    errors.email = 'Email is required!';
    isValid = false;
  } else if (!/\S+@\S+\.\S+/.test(registerForm.email)) {
    errors.email = 'Invalid email format!';
    isValid = false;
  }

  if (!registerForm.password) {
    errors.password = 'Password is required!';
    isValid = false;
  } else if (registerForm.password.length < 6) {
    errors.password = 'Password must be at least 6 characters long!';
    isValid = false;
  }

  if (registerForm.password !== registerForm.confirmPassword) {
    errors.confirmPassword = 'Passwords do not match!';
    isValid = false;
  }

  return isValid;
};

const clearError = (field) => {
  errors[field] = '';
};
const emit = defineEmits(['register']);

const handleSubmit = async () => {
  if (!validateForm()) {
    return;
  }
  toggleLoading();
  try {
     emit('register',registerForm.email,registerForm.password);
  } catch (error) {
    console.error('Registration failed:', error);
  }
};
const toggleLoading = () => {
  isLoading.value = !isLoading.value;
};

defineExpose(
  {
    toggleLoading,
  }
)

</script>

<style scoped>
.register-form {
  width: 400px;
}

.form-group {
  margin-bottom: 1rem;
}

label {
  display: block;
  margin-bottom: 0.5rem;
  color: #666;
}

input[type="text"],
input[type="email"],
input[type="password"] {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 1rem;
}

input.error {
  border-color: #ff4d4f;
}

.error-message {
  color: #ff4d4f;
  font-size: 0.875rem;
  margin-top: 0.25rem;
}

button {
  width: 100%;
  padding: 0.75rem;
  background-color: #1890ff;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 1rem;
  cursor: pointer;
}

button:hover {
  background-color: #40a9ff;
}

button:disabled {
  background-color: #bfbfbf;
  cursor: not-allowed;
}

.login-link {
  margin-top: 1rem;
  text-align: center;
  font-size: 0.875rem;
  color: #666;
}

.login-link a {
  color: #1890ff;
  text-decoration: none;
}

.login-link a:hover {
  color: #40a9ff;
}
</style>
