// src/components/LoginForm.vue
<!--
 * @Author: Richard yuetingpei888@gmail.com
 * @Date: 2025-01-31 19:27:12
 * @LastEditors: Richard yuetingpei888@gmail.com
 * @LastEditTime: 2025-02-28 09:04:37
 * @FilePath: /Resume-Modifier/src/components/LoginForm.vue
 * @Description: 
 * 
-->
<template>
  <form class="login-form" @submit.prevent="handleSubmit">
    <div class="form-group">
      <label for="email">email</label>
      <input
          type="text"
          id="email"
          v-model="loginForm.email"
          :class="{ 'error': errors.email }"
          @focus="clearError('email')"
      />
      <span class="error-message" v-if="errors.email">{{ errors.email }}</span>
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input
          type="password"
          id="password"
          v-model="loginForm.password"
          :class="{ 'error': errors.password }"
          @focus="clearError('password')"
          @keydown.enter="handleSubmit"
      />
      <span class="error-message" v-if="errors.password">{{ errors.password }}</span>
    </div>
    <div class="form-options">
    <div class="remember-me">
      <input type="checkbox" id="remember" v-model="loginForm.remember" class="remember-radio">
      <label for="remember">Remember</label>
      <router-link to="/forgot-password" class=" forgot-password" style="margin-left: auto">
        Forgot Password?
      </router-link>
    </div>

    <button type="submit" :disabled="isLoading">
      <span v-if="isLoading" class="spinner-border spinner-border-sm"></span>
      {{ isLoading ? 'Loading...' : 'Sign In' }}
    </button>
      <div class="register-link">
        Need an account?
        <router-link to="/register">Sign up</router-link>
      </div>
    </div>
  </form>
</template>

<script setup>
import {onMounted, reactive, ref} from 'vue';
onMounted(() => {
  const savedEmail = localStorage.getItem('email');
  const savedPassword = localStorage.getItem('password');

  if (savedEmail) {
    loginForm.email = savedEmail;
  }

  if (savedPassword) {
    loginForm.password = savedPassword;
  }
});
const loginForm = reactive({
    email: "",
    password: "",
    remember: false,
})
const errors = reactive({
  email: '',
  password: '',
});
const isLoading = ref(false);

const validateForm=()=>{
  let isValid = true
  errors.email="";
  errors.password="";

  if (!loginForm.email.trim()) {
    errors.email = 'Email required!';
    isValid = false;
  }

  if (!loginForm.password) {
    errors.password = 'Password required!';
    isValid = false;
  } else if (loginForm.password.length < 6) {
    errors.password = 'Password must be at least 6 characters long!';
    isValid = false;
  }
  return isValid;
}
const clearError=(field)=> {
  errors[field] = '';
};
const emit = defineEmits(['login']);
const handleSubmit= async ()=> {
  if (!validateForm()) {
    return;
  }
  toggleLoading();
  try {
    // 发送登录信息给父组件处理
    emit('login',loginForm.email,loginForm.password);
    if (loginForm.remember) {
      localStorage.setItem('email', loginForm.email);
      localStorage.setItem('password', loginForm.password);
    } else {
      localStorage.removeItem('email');
      localStorage.removeItem('password');
    }
  } catch (error) {
    console.error('表单提交失败:', error)
  }
}

const toggleLoading = () => {
  isLoading.value = !isLoading.value;
};

defineExpose(
    {
      toggleLoading,
    }
)
</script>
<style scoped>
.login-form {
  max-width: 90%;
  /* Take up 90% of the screen width */
  width: 400px;
  /* Or whatever you want the max width to be */
  margin: 0 auto;
  /* Center the form */
}

.form-group {
  max-width: 100%;
  /* Full width within the form */
  margin: auto;
  margin-bottom: 1rem;
  /* Add some spacing between form groups */
}

label {
  display: block;
  margin-bottom: 0.5rem;
  color: #666;
}

input[type="text"],
input[type="password"] {
  width: 100%;
  /* Input fields should take the full width of their container */
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 1rem;
  box-sizing: border-box;
  /* Important: Include padding and border in the width */
}

input.error {
  border-color: #ff4d4f;
}

.error-message {
  color: #ff4d4f;
  font-size: 0.875rem;
  margin-top: 0.25rem;
}

.form-options {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.remember-me {
  display: flex;
  align-items: center;
  justify-content: space-between;
  /* Push Forgot Password to the right */
  width: 100%;
  margin-bottom: 1rem;
}

.remember-me input[type="checkbox"] {
  width: auto;
  margin-right: 0.5rem;
}

.remember-radio {
  border: none;
}

button {
  width: 100%;
  padding: 0.75rem;
  background-color: #1890ff;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.3s;
}

button:hover {
  background-color: #40a9ff;
}

button:disabled {
  background-color: #bfbfbf;
  cursor: not-allowed;
}

.forgot-password {
  color: #1890ff;
  text-decoration: none;
  font-size: 0.875rem;
}

.forgot-password:hover {
  color: #40a9ff;
}

.register-link {
  margin-top: 1rem;
  text-align: center;
  font-size: 0.875rem;
  color: #666;
}

.register-link a {
  color: #1890ff;
  text-decoration: none;
  margin-left: 0.5rem;
}

.register-link a:hover {
  color: #40a9ff;
}

/* Media query for smaller screens (e.g., mobile) */
@media (max-width: 768px) {
  .login-form {
    max-width: 95%;
    /* Even wider on smaller screens */
  }

  .register-link {
    text-align: center;
  }
}
</style>

// src/components/auth/LoginForm.tsx
'use client';

import React, { useState, useEffect, ChangeEvent, FormEvent, KeyboardEvent } from 'react';
import Link from 'next/link';

interface LoginFormProps {
    onSubmit: (email: string, password: string) => Promise<void>; // Make onSubmit async
    isLoading: boolean;
}

const LoginForm: React.FC<LoginFormProps> = ({ onSubmit, isLoading }) => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [remember, setRemember] = useState(false);
    const [errors, setErrors] = useState({ email: '', password: '' });

    // Load remembered credentials on mount
    useEffect(() => {
        if (typeof window !== 'undefined') {
            const savedEmail = localStorage.getItem('rememberedEmail');
            // const savedPassword = localStorage.getItem('rememberedPassword'); // Avoid storing passwords directly
            if (savedEmail) {
                setEmail(savedEmail);
                setRemember(true); // Check the box if email was remembered
            }
            // if (savedPassword) setPassword(savedPassword);
        }
    }, []);

    const validateForm = (): boolean => {
        let isValid = true;
        const newErrors = { email: '', password: '' };

        if (!email.trim()) {
            newErrors.email = 'Email is required!';
            isValid = false;
        } else if (!/\S+@\S+\.\S+/.test(email)) {
            newErrors.email = 'Invalid email format!';
            isValid = false;
        }


        if (!password) {
            newErrors.password = 'Password is required!';
            isValid = false;
        } else if (password.length < 6) {
            newErrors.password = 'Password must be at least 6 characters long!';
            isValid = false;
        }

        setErrors(newErrors);
        return isValid;
    };

    const clearError = (field: keyof typeof errors) => {
        setErrors((prev) => ({ ...prev, [field]: '' }));
    };

    const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!validateForm()) {
            return;
        }

        // Handle remember me logic before submitting
        if (remember) {
            localStorage.setItem('rememberedEmail', email);
            // localStorage.setItem('rememberedPassword', password); // Avoid storing password
        } else {
            localStorage.removeItem('rememberedEmail');
            // localStorage.removeItem('rememberedPassword');
        }

        await onSubmit(email, password); // Call the async onSubmit prop
    };

    const handleKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
        if (event.key === 'Enter') {
            // Create a synthetic event or directly call validation and submit logic
            if (validateForm()) {
                if (remember) localStorage.setItem('rememberedEmail', email);
                else localStorage.removeItem('rememberedEmail');
                onSubmit(email, password);
            }
        }
    };


    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            {/* Email Field */}
            <div>
                <label htmlFor="email" className="form-label">
                    Email
                </label>
                <input
                    type="email" // Use type="email" for better validation/mobile input
                    id="email"
                    value={email}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
                    onFocus={() => clearError('email')}
                    className={`form-control ${errors.email ? 'border-red-500' : 'border-gray-300'}`}
                    aria-describedby="email-error"
                    aria-invalid={!!errors.email}
                    autoComplete="email"
                />
                {errors.email && (
                    <p id="email-error" className="mt-1 text-sm text-red-600">
                        {errors.email}
                    </p>
                )}
            </div>

            {/* Password Field */}
            <div>
                <label htmlFor="password" className="form-label">
                    Password
                </label>
                <input
                    type="password"
                    id="password"
                    value={password}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
                    onFocus={() => clearError('password')}
                    onKeyDown={handleKeyDown} // Add keydown listener
                    className={`form-control ${errors.password ? 'border-red-500' : 'border-gray-300'}`}
                    aria-describedby="password-error"
                    aria-invalid={!!errors.password}
                    autoComplete="current-password"
                />
                {errors.password && (
                    <p id="password-error" className="mt-1 text-sm text-red-600">
                        {errors.password}
                    </p>
                )}
            </div>

            {/* Remember Me & Forgot Password */}
            <div className="flex items-center justify-between">
                <div className="flex items-center">
                    <input
                        id="remember"
                        type="checkbox"
                        checked={remember}
                        onChange={(e: ChangeEvent<HTMLInputElement>) => setRemember(e.target.checked)}
                        className="form-check-input" // Use Tailwind component class if defined, or apply utilities directly
                    />
                    <label htmlFor="remember" className="form-check-label">
                        Remember me
                    </label>
                </div>
                <Link href="/forgot-password" // Update link if needed
                      className="text-sm font-medium text-blue-600 hover:text-blue-700">
                    Forgot Password?
                </Link>
            </div>

            {/* Submit Button */}
            <button
                type="submit"
                disabled={isLoading}
                className="w-full btn-primary flex justify-center items-center" // Ensure button uses full width and centers content
            >
                {isLoading ? (
                    <>
                        <span className="spinner-border spinner-border-sm mr-2" role="status" aria-hidden="true"></span>
                        Loading...
                    </>
                ) : (
                    'Sign In'
                )}
            </button>

            {/* Register Link */}
            <div className="text-sm text-center text-gray-600">
                Need an account?{' '}
                <Link href="/register" className="font-medium text-blue-600 hover:text-blue-700">
                    Sign up
                </Link>
            </div>
        </form>
    );
};

export default LoginForm;
